language: node_js
node_js:
  - 6
cache: yarn
script:
  - npm test
  - npm run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: build
  on:
    branch: master
  email: me@helior.info
  name: Helior Colorado
  fqdn: kindafeelinit.com
